// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OssColumns holds the columns for the "oss" table.
	OssColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// OssTable holds the schema information for the "oss" table.
	OssTable = &schema.Table{
		Name:        "oss",
		Columns:     OssColumns,
		PrimaryKey:  []*schema.Column{OssColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OssTable,
	}
)

func init() {
}
