// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/rickypai/ent-test/ent/migrate"

	"github.com/rickypai/ent-test/ent/os"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// OS is the client for interacting with the OS builders.
	OS *OSClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.OS = NewOSClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		OS:     NewOSClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		OS:     NewOSClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		OS.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.OS.Use(hooks...)
}

// OSClient is a client for the OS schema.
type OSClient struct {
	config
}

// NewOSClient returns a client for the OS from the given config.
func NewOSClient(c config) *OSClient {
	return &OSClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `os.Hooks(f(g(h())))`.
func (c *OSClient) Use(hooks ...Hook) {
	c.hooks.OS = append(c.hooks.OS, hooks...)
}

// Create returns a create builder for OS.
func (c *OSClient) Create() *OSCreate {
	mutation := newOSMutation(c.config, OpCreate)
	return &OSCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OS entities.
func (c *OSClient) CreateBulk(builders ...*OSCreate) *OSCreateBulk {
	return &OSCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OS.
func (c *OSClient) Update() *OSUpdate {
	mutation := newOSMutation(c.config, OpUpdate)
	return &OSUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OSClient) UpdateOne(o *OS) *OSUpdateOne {
	mutation := newOSMutation(c.config, OpUpdateOne, withOS(o))
	return &OSUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OSClient) UpdateOneID(id int) *OSUpdateOne {
	mutation := newOSMutation(c.config, OpUpdateOne, withOSID(id))
	return &OSUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OS.
func (c *OSClient) Delete() *OSDelete {
	mutation := newOSMutation(c.config, OpDelete)
	return &OSDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *OSClient) DeleteOne(o *OS) *OSDeleteOne {
	return c.DeleteOneID(o.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *OSClient) DeleteOneID(id int) *OSDeleteOne {
	builder := c.Delete().Where(os.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OSDeleteOne{builder}
}

// Query returns a query builder for OS.
func (c *OSClient) Query() *OSQuery {
	return &OSQuery{config: c.config}
}

// Get returns a OS entity by its id.
func (c *OSClient) Get(ctx context.Context, id int) (*OS, error) {
	return c.Query().Where(os.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OSClient) GetX(ctx context.Context, id int) *OS {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OSClient) Hooks() []Hook {
	return c.hooks.OS
}
