// Code generated by entc, DO NOT EDIT.

package os

const (
	// Label holds the string label denoting the os type in the database.
	Label = "os"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the os in the database.
	Table = "oss"
)

// Columns holds all SQL columns for os fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
